#!/usr/bin/env bash
# Saya akan membuat program yang outputnya sama sesuai soal.

read -r expression
# Membaca ekspresi matematika dari input

result=$(echo "System.out.println((double)($expression));" | jshell -s - | tail -n 1)
# Menghitung ekspresi menggunakan JShell, tail -n digunakan untuk mengambil hasil akhir

if [[ $result == *.0 ]]; then
    result=${result%.0}
fi
# Jika hasil berupa bilangan bulat seperti 2.0, hilangkan .0

echo "$result"
# Menampilkan hasil akhir/outputnya
